apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qjs
resources:
- deployment.yaml
- service.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: quake3-server-config 
  files:
    # configfile is used as key
    - configs/configmap.yaml
